2017-01-14 10:58:19,039 manager INFO 1.1.0
2017-01-14 10:58:19,039 manager INFO Copyright (C) 2003-2010
2017-01-14 10:58:19,039 manager INFO   Noriaki Ando
2017-01-14 10:58:19,039 manager INFO   Intelligent Systems Research Institute, AIST
2017-01-14 10:58:19,039 manager INFO Manager starting.
2017-01-14 10:58:19,039 manager INFO Starting local logging.
2017-01-14 10:58:19,040 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2017-01-14 10:58:19,043 ManagerServant INFO Master manager not found
2017-01-14 10:58:19,044 manager WARNING Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 13] Permission denied: '/var/log/rtcmanager.ref'

2017-01-14 10:58:19,044 LocalServiceAdmin INFO All the local services are enabled.
2017-01-14 10:58:19,046 manager INFO Component type conf file: ObjTester.conf loaded.
2017-01-14 10:58:19,048 ec_base INFO setRate(1000000.000000) done
2017-01-14 10:58:19,048 ec_base INFO setRate(1000.000000) done
2017-01-14 10:58:19,048 rtobject INFO 1 execution context was created.
2017-01-14 10:58:19,049 rtobject INFO Initial active configuration set is default-set.
2017-01-14 10:58:25,960 SdoServiceAdmin WARNING No available SDO service in the factory: 
2017-01-14 10:58:25,960 SdoServiceAdmin ERROR type  already exists.
2017-01-14 10:58:25,961 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2017-01-14 10:58:25,961 SdoServiceAdmin ERROR type 725a1a3f-4082-40c5-9d4c-eb91a8c69ca1 already exists.
2017-01-14 10:58:25,968 ec_base INFO setRate(1000.000000) done
2017-01-14 10:58:29,140 ObjectDetectionService WARNING Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/PortBase.py", line 2262, in checkPorts
    if port._non_existent():
  File "/usr/lib/python2.7/dist-packages/omniORB/CORBA.py", line 775, in _non_existent
    return _omnipy.nonExistent(self)
COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)

2017-01-14 10:58:29,140 ObjectDetectionService WARNING Dead connection: 84417990-d9f5-11e6-ad72-8c89a5e21530
2017-01-14 10:58:29,140 ObjectDetectionService WARNING Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/PortBase.py", line 1624, in disconnectNext
    return p.notify_disconnect(connector_profile.connector_id)
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/RTM_IDL/RTC_idl.py", line 1226, in notify_disconnect
    return _omnipy.invoke(self, "notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2017-01-14 11:07:35,801 SdoServiceAdmin WARNING No available SDO service in the factory: 
2017-01-14 11:07:35,801 SdoServiceAdmin ERROR type  already exists.
2017-01-14 11:07:35,802 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2017-01-14 11:07:35,802 SdoServiceAdmin ERROR type adb0a9e7-cfb4-4c55-ae93-208f37e8543d already exists.
2017-01-14 11:07:35,809 ec_base INFO setRate(1000.000000) done
2017-01-14 11:07:36,609 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2017-01-14 11:07:39,816 ObjectDetectionService WARNING Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/PortBase.py", line 2262, in checkPorts
    if port._non_existent():
  File "/usr/lib/python2.7/dist-packages/omniORB/CORBA.py", line 775, in _non_existent
    return _omnipy.nonExistent(self)
COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)

2017-01-14 11:07:39,816 ObjectDetectionService WARNING Dead connection: 84417990-d9f5-11e6-ad72-8c89a5e21530
2017-01-14 11:07:39,817 ObjectDetectionService WARNING Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/PortBase.py", line 1624, in disconnectNext
    return p.notify_disconnect(connector_profile.connector_id)
  File "/usr/lib/python2.7/dist-packages/OpenRTM_aist/RTM_IDL/RTC_idl.py", line 1226, in notify_disconnect
    return _omnipy.invoke(self, "notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2017-01-14 11:08:00,719 ec_worker WARNING ExecutionContext is already stopped.
2017-01-14 11:08:00,719 ec_base ERROR Invoking on_shutdown() for each RTC failed.
